### ISSUE TITLE
Auth.js support

### ISSUE THREAD

**Issue by xmlking** [AmruthPillai/next-auth-hasura-adapter#1]
NextAuth moved to  [Auth.js](https://authjs.dev/) with new multi framework API.

We are using with sveltekit and realized this lib no more working. 
Please support now Auth.js as well.

**Comment by xmlking** [comment]
I think this should work... 
```
import {
  Adapter,
  AdapterAccount,
  AdapterSession,
  AdapterUser,
  VerificationToken,
} from "@auth/core/adapters";
```

**Comment by amruthpillai** [comment]
Could you check if v2.0.0 now has the changes required to support Auth.js?
This PR comes with a couple of migration changes: https://github.com/AmruthPillai/next-auth-hasura-adapter/pull/2

**Comment by xmlking** [comment]
Will test and let you know.
Thanks for your continuous support.
